const meta = {
  "ZafkChannelID": "ZafkChannelID",
  "ZcategoryChannels": "ZcategoryChannels",
  "ZcategoryCount": "ZcategoryCount",
  "ZcategoryID": "ZcategoryID",
  "ZchannelCount": "ZchannelCount",
  "ZchannelCreated": "ZchannelCreated",
  "ZchannelExists": "ZchannelExists",
  "ZchannelName": "ZchannelName",
  "ZchannelNames": "ZchannelNames",
  "ZchannelPosition": "ZchannelPosition",
  "ZchannelTopic": "ZchannelTopic",
  "ZchannelType": "ZchannelType",
  "ZchannelWebhooks": "ZchannelWebhooks",
  "ZcreateChannel": "ZcreateChannel",
  "ZdeleteChannels": "ZdeleteChannels",
  "ZdeleteChannelsByName": "ZdeleteChannelsByName",
  "ZdmChannelID": "ZdmChannelID",
  "ZeditChannelPerms": "ZeditChannelPerms",
  "ZgetSlowmode": "ZgetSlowmode",
  "ZisNSFW": "ZisNSFW",
  "ZlastMessageID": "ZlastMessageID",
  "ZlastPinTimestamp": "ZlastPinTimestamp",
  "ZmodifyChannel": "ZmodifyChannel",
  "ZparentID": "ZparentID",
  "ZrulesChannelID": "ZrulesChannelID",
  "ZserverChannels": "ZserverChannels",
  "ZslowMode": "ZslowMode",
  "ZsystemChannelID": "ZsystemChannelID",
  "ZvoiceUserLimit": "ZvoiceUserLimit"
};

export default meta;