export default {
  "ZcolorRole": "ZcolorRole",
  "ZcreateRole": "ZcreateRole",
  "ZdeleteRole": "ZdeleteRole",
  "ZhasRole": "ZhasRole",
  "ZhighestRole": "ZhighestRole",
  "ZhighestRoleWithPerms": "ZhighestRoleWithPerms",
  "ZisHoisted": "ZisHoisted",
  "ZisMentionable": "ZisMentionable",
  "ZlowestRole": "ZlowestRole",
  "ZlowestRoleWithPerms": "ZlowestRoleWithPerms",
  "ZmodifyRole": "ZmodifyRole",
  "ZmodifyRolePerms": "ZmodifyRolePerms",
  "ZroleColor": "ZroleColor",
  "ZroleCount": "ZroleCount",
  "ZroleExists": "ZroleExists",
  "ZroleGrant": "ZroleGrant",
  "ZroleMemberCount": "ZroleMemberCount",
  "ZroleMembers": "ZroleMembers",
  "ZroleName": "ZroleName",
  "ZroleNames": "ZroleNames",
  "ZrolePerms": "ZrolePerms",
  "ZrolePosition": "ZrolePosition",
  "ZsetUserRoles": "ZsetUserRoles",
  "ZuserRoles": "ZuserRoles"
}