export default {
  "ZjsonArray": "ZjsonArray",
  "ZjsonArrayAppend": "ZjsonArrayAppend",
  "ZjsonArrayCount": "ZjsonArrayCount",
  "ZjsonArrayIndex": "ZjsonArrayIndex",
  "ZjsonArrayPop": "ZjsonArrayPop",
  "ZjsonArrayReverse": "ZjsonArrayReverse",
  "ZjsonArrayShift": "ZjsonArrayShift",
  "ZjsonArraySort": "ZjsonArraySort",
  "ZjsonArrayUnshift": "ZjsonArrayUnshift",
  "ZjsonClear": "ZjsonClear",
  "ZjsonExists": "ZjsonExists",
  "ZjsonGet": "ZjsonGet",
  "ZjsonJoinArray": "ZjsonJoinArray",
  "ZjsonParse": "ZjsonParse",
  "ZjsonPretty": "ZjsonPretty",
  "ZjsonSet": "ZjsonSet",
  "ZjsonStringify": "ZjsonStringify",
  "ZjsonUnset": "ZjsonUnset"
}