export default {
  "onBanAdd": "onBanAdd",
  "onBanRemove": "onBanRemove",
  "onChannelCreate": "onChannelCreate",
  "onChannelDelete": "onChannelDelete",
  "onChannelUpdate": "onChannelUpdate",
  "onGuildUpdate": "onGuildUpdate",
  "onMemberJoin": "onMemberJoin",
  "onMemberLeave": "onMemberLeave",
  "onMemberUpdate": "onMemberUpdate",
  "onMessage": "onMessage",
  "onMessageDelete": "onMessageDelete",
  "onMessageEdit": "onMessageEdit",
  "onReactionAdd": "onReactionAdd",
  "onReactionRemove": "onReactionRemove",
  "onRoleCreate": "onRoleCreate",
  "onRoleDelete": "onRoleDelete",
  "onRoleUpdate": "onRoleUpdate",
  "onVoiceStateUpdate": "onVoiceStateUpdate"
}