const meta = {
  "onAuditLogEntry": "onAuditLogEntry",
  "onAutomodAction": "onAutomodAction",
  "onAutomodRuleCreate": "onAutomodRuleCreate",
  "onAutomodRuleDelete": "onAutomodRuleDelete",
  "onAutomodRuleUpdate": "onAutomodRuleUpdate",
  "onBanAdd": "onBanAdd",
  "onBanRemove": "onBanRemove",
  "onBoostAdd": "onBoostAdd",
  "onBoostRemove": "onBoostRemove",
  "onBotJoin": "onBotJoin",
  "onBotLeave": "onBotLeave",
  "onChannelCreate": "onChannelCreate",
  "onChannelDelete": "onChannelDelete",
  "onChannelUpdate": "onChannelUpdate",
  "onGuildUpdate": "onGuildUpdate",
  "onMemberJoin": "onMemberJoin",
  "onMemberLeave": "onMemberLeave",
  "onMemberUpdate": "onMemberUpdate",
  "onMessage": "onMessage",
  "onMessageDelete": "onMessageDelete",
  "onMessageEdit": "onMessageEdit",
  "onPollVoteAdd": "onPollVoteAdd",
  "onPollVoteRemove": "onPollVoteRemove",
  "onReactionAdd": "onReactionAdd",
  "onReactionRemove": "onReactionRemove",
  "onRoleCreate": "onRoleCreate",
  "onRoleDelete": "onRoleDelete",
  "onRoleUpdate": "onRoleUpdate",
  "onStageInstanceCreate": "onStageInstanceCreate",
  "onStageInstanceDelete": "onStageInstanceDelete",
  "onStageInstanceUpdate": "onStageInstanceUpdate",
  "onThreadCreate": "onThreadCreate",
  "onThreadDelete": "onThreadDelete",
  "onThreadUpdate": "onThreadUpdate",
  "onVoiceStateUpdate": "onVoiceStateUpdate"
};

export default meta;