const meta = {
  "math": "Math",
  "components": "Components",
  "reactions": "Reactions",
  "emojis": "Emojis",
  "embeds": "Embeds",
  "channels": "Channels",
  "servers": "Servers",
  "bot": "Bot",
  "context": "Context",
  "string": "String",
  "control": "Control",
  "runtime": "Runtime",
  "audit": "Audit",
  "automod": "Automod",
  "moderation": "Moderation",
  "utility": "Utility",
  "blacklists": "Blacklists",
  "cooldown": "Cooldown",
  "users": "Users",
  "id": "Id",
  "invites": "Invites",
  "permissions": "Permissions",
  "roles": "Roles",
  "events": "Events",
  "forums": "Forums",
  "time": "Time",
  "message": "Message",
  "stickers": "Stickers",
  "textsplit": "Textsplit",
  "threads": "Threads",
  "errors": "Errors",
  "special": "Special",
  "loops": "Loops",
  "variables": "Variables",
  "http": "Http",
  "voice": "Voice",
  "json": "Json",
  "polls": "Polls",
  "random": "Random",
  "actions": "Actions",
  "soundboard": "Soundboard",
  "stage": "Stage"
};

export default meta;