const meta = {
  "ZaddButton": "ZaddButton",
  "ZaddMentionableSelect": "ZaddMentionableSelect",
  "ZaddRoleSelect": "ZaddRoleSelect",
  "ZaddSelectMenuOption": "ZaddSelectMenuOption",
  "ZaddTextInput": "ZaddTextInput",
  "ZaddUserSelect": "ZaddUserSelect",
  "ZcustomID": "ZcustomID",
  "Zdefer": "Zdefer",
  "ZeditButton": "ZeditButton",
  "ZeditSelectMenu": "ZeditSelectMenu",
  "ZeditSelectMenuOption": "ZeditSelectMenuOption",
  "ZgetMentionableSelectUserCount": "ZgetMentionableSelectUserCount",
  "ZgetMentionableSelectUserID": "ZgetMentionableSelectUserID",
  "ZgetMentionableSelectUserIDs": "ZgetMentionableSelectUserIDs",
  "ZgetRoleSelectRoleCount": "ZgetRoleSelectRoleCount",
  "ZgetRoleSelectRoleID": "ZgetRoleSelectRoleID",
  "ZgetRoleSelectRoleIDs": "ZgetRoleSelectRoleIDs",
  "ZgetUserSelectUserCount": "ZgetUserSelectUserCount",
  "ZgetUserSelectUserID": "ZgetUserSelectUserID",
  "ZgetUserSelectUserIDs": "ZgetUserSelectUserIDs",
  "ZinputValue": "ZinputValue",
  "ZnewModal": "ZnewModal",
  "ZnewSelectMenu": "ZnewSelectMenu",
  "ZremoveAllComponents": "ZremoveAllComponents",
  "ZremoveButtons": "ZremoveButtons",
  "ZremoveComponent": "ZremoveComponent"
};

export default meta;